import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();
  const isLoggedIn = !!session?.user;

  console.log(session);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="flex gap-4 p-4">
          <Link href="/">Home</Link>
          <Link href="/about">About</Link>
          {isLoggedIn ? (
            <>
              <Link href="/signout">Sign out</Link>
              <Link href="/admin">Admin</Link>
            </>
          ) : (
            <Link href="/login">Log in</Link>
          )}
        </header>
        {children}
      </body>
    </html>
  );
}

